import Head from 'next/head';
import ImageUpload from '@/features/scan/components/ImageUpload';
import { NextPageWithLayout } from '@/pages/_app';
import Layout from '@/common/components/Layout';
import { ReactElement } from 'react';
import HistoryScanList from '@/features/history/components/HistoryScanList';

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Nhận diện bệnh cây lúa</title>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#fff" />
        {/* <meta name="theme-color" content="#ffffff" /> */}
        {/* <meta name="theme-color" content="rgba(255,255,255, 0.3)" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageUpload />
      <HistoryScanList historyList={[]} />
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Page;
