import Head from 'next/head';
import { NextPageWithLayout } from '@/pages/_app';
import Layout from '@/common/components/Layout';
import { ReactElement } from 'react';
import WebCam from '@/features/scan/components/WebCam';

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Nhận diện bệnh cây lúa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="rgba(0,0,0,0.8)" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebCam />
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout showBackButton>{page}</Layout>;
};

export default Page;
