import Head from 'next/head';
import { NextPageWithLayout } from '@/pages/_app';
import Layout from '@/common/components/Layout';
import { ReactElement, useEffect } from 'react';
import WebCam from '@/features/scan/components/WebCam';

const Page: NextPageWithLayout = () => {
  useEffect(() => {
    // document.documentElement.requestFullscreen();
  }, []);

  return (
    <>
      <Head>
        <title>Nhận diện bệnh cây lúa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#fff" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebCam />
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout showBackButton textDark={false}>
      {page}
    </Layout>
  );
};

export default Page;
